/*
 * This file is generated by jOOQ.
 */
package com.fenrir.core.database;


import com.fenrir.core.database.tables.AlbumVisibility;
import com.fenrir.core.database.tables.Albums;
import com.fenrir.core.database.tables.Roles;
import com.fenrir.core.database.tables.Startup;
import com.fenrir.core.database.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.album_visibility</code>.
     */
    public static final AlbumVisibility ALBUM_VISIBILITY = AlbumVisibility.ALBUM_VISIBILITY;

    /**
     * The table <code>public.albums</code>.
     */
    public static final Albums ALBUMS = Albums.ALBUMS;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.startup</code>.
     */
    public static final Startup STARTUP = Startup.STARTUP;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
