/*
 * This file is generated by jOOQ.
 */
package com.fenrir.core.database.tables.records;


import com.fenrir.core.database.tables.AlbumVisibility;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AlbumVisibilityRecord extends UpdatableRecordImpl<AlbumVisibilityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.album_visibility.id</code>.
     */
    public AlbumVisibilityRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.album_visibility.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.album_visibility.name</code>.
     */
    public AlbumVisibilityRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.album_visibility.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlbumVisibilityRecord
     */
    public AlbumVisibilityRecord() {
        super(AlbumVisibility.ALBUM_VISIBILITY);
    }

    /**
     * Create a detached, initialised AlbumVisibilityRecord
     */
    public AlbumVisibilityRecord(Long id, String name) {
        super(AlbumVisibility.ALBUM_VISIBILITY);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AlbumVisibilityRecord
     */
    public AlbumVisibilityRecord(com.fenrir.core.database.tables.pojos.AlbumVisibility value) {
        super(AlbumVisibility.ALBUM_VISIBILITY);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            resetChangedOnNotNull();
        }
    }
}
