/*
 * This file is generated by jOOQ.
 */
package com.fenrir.core.database.tables.records;


import com.fenrir.core.database.tables.Albums;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AlbumsRecord extends UpdatableRecordImpl<AlbumsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.albums.id</code>.
     */
    public AlbumsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.albums.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.albums.name</code>.
     */
    public AlbumsRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.albums.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.albums.description</code>.
     */
    public AlbumsRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.albums.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.albums.updated_at</code>.
     */
    public AlbumsRecord setUpdatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.albums.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.albums.created_at</code>.
     */
    public AlbumsRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.albums.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.albums.owner_id</code>.
     */
    public AlbumsRecord setOwnerId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.albums.owner_id</code>.
     */
    public Long getOwnerId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.albums.visibility_id</code>.
     */
    public AlbumsRecord setVisibilityId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.albums.visibility_id</code>.
     */
    public Long getVisibilityId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlbumsRecord
     */
    public AlbumsRecord() {
        super(Albums.ALBUMS);
    }

    /**
     * Create a detached, initialised AlbumsRecord
     */
    public AlbumsRecord(Long id, String name, String description, LocalDateTime updatedAt, LocalDateTime createdAt, Long ownerId, Long visibilityId) {
        super(Albums.ALBUMS);

        setId(id);
        setName(name);
        setDescription(description);
        setUpdatedAt(updatedAt);
        setCreatedAt(createdAt);
        setOwnerId(ownerId);
        setVisibilityId(visibilityId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AlbumsRecord
     */
    public AlbumsRecord(com.fenrir.core.database.tables.pojos.Albums value) {
        super(Albums.ALBUMS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setUpdatedAt(value.getUpdatedAt());
            setCreatedAt(value.getCreatedAt());
            setOwnerId(value.getOwnerId());
            setVisibilityId(value.getVisibilityId());
            resetChangedOnNotNull();
        }
    }
}
