/*
 * This file is generated by jOOQ.
 */
package com.fenrir.core.database.tables.records;


import com.fenrir.core.database.tables.AlbumVisibility;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlbumVisibilityRecord extends UpdatableRecordImpl<AlbumVisibilityRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.album_visibility.id</code>.
     */
    public AlbumVisibilityRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.album_visibility.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.album_visibility.name</code>.
     */
    public AlbumVisibilityRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.album_visibility.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AlbumVisibility.ALBUM_VISIBILITY.ID;
    }

    @Override
    public Field<String> field2() {
        return AlbumVisibility.ALBUM_VISIBILITY.NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public AlbumVisibilityRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AlbumVisibilityRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AlbumVisibilityRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlbumVisibilityRecord
     */
    public AlbumVisibilityRecord() {
        super(AlbumVisibility.ALBUM_VISIBILITY);
    }

    /**
     * Create a detached, initialised AlbumVisibilityRecord
     */
    public AlbumVisibilityRecord(Long id, String name) {
        super(AlbumVisibility.ALBUM_VISIBILITY);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AlbumVisibilityRecord
     */
    public AlbumVisibilityRecord(com.fenrir.core.database.tables.pojos.AlbumVisibility value) {
        super(AlbumVisibility.ALBUM_VISIBILITY);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            resetChangedOnNotNull();
        }
    }
}
