/*
 * This file is generated by jOOQ.
 */
package com.fenrir.core.database.tables.records;


import com.fenrir.core.database.tables.Startup;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StartupRecord extends TableRecordImpl<StartupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.startup.name</code>.
     */
    public StartupRecord setName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.startup.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.startup.value</code>.
     */
    public StartupRecord setValue(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.startup.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StartupRecord
     */
    public StartupRecord() {
        super(Startup.STARTUP);
    }

    /**
     * Create a detached, initialised StartupRecord
     */
    public StartupRecord(String name, String value) {
        super(Startup.STARTUP);

        setName(name);
        setValue(value);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised StartupRecord
     */
    public StartupRecord(com.fenrir.core.database.tables.pojos.Startup value) {
        super(Startup.STARTUP);

        if (value != null) {
            setName(value.getName());
            setValue(value.getValue());
            resetChangedOnNotNull();
        }
    }
}
