/*
 * This file is generated by jOOQ.
 */
package com.fenrir.core.database.tables.records;


import com.fenrir.core.database.tables.Users;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.users.id</code>.
     */
    public UsersRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.users.code</code>.
     */
    public UsersRecord setCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.users.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.users.auth_type</code>.
     */
    public UsersRecord setAuthType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.users.auth_type</code>.
     */
    public String getAuthType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.users.external_id</code>.
     */
    public UsersRecord setExternalId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.users.external_id</code>.
     */
    public String getExternalId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.users.external_name</code>.
     */
    public UsersRecord setExternalName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.users.external_name</code>.
     */
    public String getExternalName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.users.name</code>.
     */
    public UsersRecord setName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.users.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.users.email</code>.
     */
    public UsersRecord setEmail(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.users.email</code>.
     */
    public String getEmail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.users.verified</code>.
     */
    public UsersRecord setVerified(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.users.verified</code>.
     */
    public Boolean getVerified() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.users.enabled</code>.
     */
    public UsersRecord setEnabled(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.users.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.users.updated_at</code>.
     */
    public UsersRecord setUpdatedAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.users.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.users.created_at</code>.
     */
    public UsersRecord setCreatedAt(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.users.role_id</code>.
     */
    public UsersRecord setRoleId(Long value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.users.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.users.password</code>.
     */
    public UsersRecord setPassword(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.users.password</code>.
     */
    public String getPassword() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Long id, String code, String authType, String externalId, String externalName, String name, String email, Boolean verified, Boolean enabled, LocalDateTime updatedAt, LocalDateTime createdAt, Long roleId, String password) {
        super(Users.USERS);

        setId(id);
        setCode(code);
        setAuthType(authType);
        setExternalId(externalId);
        setExternalName(externalName);
        setName(name);
        setEmail(email);
        setVerified(verified);
        setEnabled(enabled);
        setUpdatedAt(updatedAt);
        setCreatedAt(createdAt);
        setRoleId(roleId);
        setPassword(password);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(com.fenrir.core.database.tables.pojos.Users value) {
        super(Users.USERS);

        if (value != null) {
            setId(value.getId());
            setCode(value.getCode());
            setAuthType(value.getAuthType());
            setExternalId(value.getExternalId());
            setExternalName(value.getExternalName());
            setName(value.getName());
            setEmail(value.getEmail());
            setVerified(value.getVerified());
            setEnabled(value.getEnabled());
            setUpdatedAt(value.getUpdatedAt());
            setCreatedAt(value.getCreatedAt());
            setRoleId(value.getRoleId());
            setPassword(value.getPassword());
            resetChangedOnNotNull();
        }
    }
}
