spring:
  cloud:
    gateway:
      routes:
        - id: core
          uri: lb://core
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

jwt:
  secret: 'FZNdMfiY82GLxjG6WF77xuN34E8izBFqatWVY5hU1Pv0LxeLLZjAkh7dKi0Z'
  expiration: 172800000

management:
  endpoints:
    web:
      exposure:
        include: '*'