/*
 * This file is generated by jOOQ.
 */
package com.fenrir.core.database.tables;


import com.fenrir.core.database.Public;
import com.fenrir.core.database.tables.records.AlbumsRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Albums extends TableImpl<AlbumsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.albums</code>
     */
    public static final Albums ALBUMS = new Albums();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlbumsRecord> getRecordType() {
        return AlbumsRecord.class;
    }

    /**
     * The column <code>public.albums.id</code>.
     */
    public final TableField<AlbumsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.albums.name</code>.
     */
    public final TableField<AlbumsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.albums.description</code>.
     */
    public final TableField<AlbumsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>public.albums.updated_at</code>.
     */
    public final TableField<AlbumsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.albums.created_at</code>.
     */
    public final TableField<AlbumsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.albums.owner_id</code>.
     */
    public final TableField<AlbumsRecord, Long> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.albums.visibility_id</code>.
     */
    public final TableField<AlbumsRecord, Long> VISIBILITY_ID = createField(DSL.name("visibility_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private Albums(Name alias, Table<AlbumsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Albums(Name alias, Table<AlbumsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.albums</code> table reference
     */
    public Albums(String alias) {
        this(DSL.name(alias), ALBUMS);
    }

    /**
     * Create an aliased <code>public.albums</code> table reference
     */
    public Albums(Name alias) {
        this(alias, ALBUMS);
    }

    /**
     * Create a <code>public.albums</code> table reference
     */
    public Albums() {
        this(DSL.name("albums"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AlbumsRecord, Long> getIdentity() {
        return (Identity<AlbumsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AlbumsRecord> getPrimaryKey() {
        return Internal.createUniqueKey(Albums.ALBUMS, DSL.name("pk_albums"), new TableField[] { Albums.ALBUMS.ID }, true);
    }

    @Override
    public Albums as(String alias) {
        return new Albums(DSL.name(alias), this);
    }

    @Override
    public Albums as(Name alias) {
        return new Albums(alias, this);
    }

    @Override
    public Albums as(Table<?> alias) {
        return new Albums(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Albums rename(String name) {
        return new Albums(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Albums rename(Name name) {
        return new Albums(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Albums rename(Table<?> name) {
        return new Albums(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Albums where(Condition condition) {
        return new Albums(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Albums where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Albums where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Albums where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Albums where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Albums where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Albums where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Albums where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Albums whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Albums whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
