/*
 * This file is generated by jOOQ.
 */
package com.fenrir.core.database.tables;


import com.fenrir.core.database.Public;
import com.fenrir.core.database.tables.records.AlbumVisibilityRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AlbumVisibility extends TableImpl<AlbumVisibilityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.album_visibility</code>
     */
    public static final AlbumVisibility ALBUM_VISIBILITY = new AlbumVisibility();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlbumVisibilityRecord> getRecordType() {
        return AlbumVisibilityRecord.class;
    }

    /**
     * The column <code>public.album_visibility.id</code>.
     */
    public final TableField<AlbumVisibilityRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.album_visibility.name</code>.
     */
    public final TableField<AlbumVisibilityRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    private AlbumVisibility(Name alias, Table<AlbumVisibilityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AlbumVisibility(Name alias, Table<AlbumVisibilityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.album_visibility</code> table reference
     */
    public AlbumVisibility(String alias) {
        this(DSL.name(alias), ALBUM_VISIBILITY);
    }

    /**
     * Create an aliased <code>public.album_visibility</code> table reference
     */
    public AlbumVisibility(Name alias) {
        this(alias, ALBUM_VISIBILITY);
    }

    /**
     * Create a <code>public.album_visibility</code> table reference
     */
    public AlbumVisibility() {
        this(DSL.name("album_visibility"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AlbumVisibilityRecord, Long> getIdentity() {
        return (Identity<AlbumVisibilityRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AlbumVisibilityRecord> getPrimaryKey() {
        return Internal.createUniqueKey(AlbumVisibility.ALBUM_VISIBILITY, DSL.name("pk_alvisibility"), new TableField[] { AlbumVisibility.ALBUM_VISIBILITY.ID }, true);
    }

    @Override
    public List<UniqueKey<AlbumVisibilityRecord>> getUniqueKeys() {
        return Arrays.asList(
            Internal.createUniqueKey(AlbumVisibility.ALBUM_VISIBILITY, DSL.name("uq_alvisibility_name"), new TableField[] { AlbumVisibility.ALBUM_VISIBILITY.NAME }, true)
        );
    }

    @Override
    public AlbumVisibility as(String alias) {
        return new AlbumVisibility(DSL.name(alias), this);
    }

    @Override
    public AlbumVisibility as(Name alias) {
        return new AlbumVisibility(alias, this);
    }

    @Override
    public AlbumVisibility as(Table<?> alias) {
        return new AlbumVisibility(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AlbumVisibility rename(String name) {
        return new AlbumVisibility(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AlbumVisibility rename(Name name) {
        return new AlbumVisibility(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AlbumVisibility rename(Table<?> name) {
        return new AlbumVisibility(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumVisibility where(Condition condition) {
        return new AlbumVisibility(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumVisibility where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumVisibility where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumVisibility where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AlbumVisibility where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AlbumVisibility where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AlbumVisibility where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AlbumVisibility where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumVisibility whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumVisibility whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
