/*
 * This file is generated by jOOQ.
 */
package com.fenrir.core.database.tables;


import com.fenrir.core.database.Public;
import com.fenrir.core.database.tables.records.AlbumVisibilityRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlbumVisibility extends TableImpl<AlbumVisibilityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.album_visibility</code>
     */
    public static final AlbumVisibility ALBUM_VISIBILITY = new AlbumVisibility();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlbumVisibilityRecord> getRecordType() {
        return AlbumVisibilityRecord.class;
    }

    /**
     * The column <code>public.album_visibility.id</code>.
     */
    public final TableField<AlbumVisibilityRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.album_visibility.name</code>.
     */
    public final TableField<AlbumVisibilityRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    private AlbumVisibility(Name alias, Table<AlbumVisibilityRecord> aliased) {
        this(alias, aliased, null);
    }

    private AlbumVisibility(Name alias, Table<AlbumVisibilityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.album_visibility</code> table reference
     */
    public AlbumVisibility(String alias) {
        this(DSL.name(alias), ALBUM_VISIBILITY);
    }

    /**
     * Create an aliased <code>public.album_visibility</code> table reference
     */
    public AlbumVisibility(Name alias) {
        this(alias, ALBUM_VISIBILITY);
    }

    /**
     * Create a <code>public.album_visibility</code> table reference
     */
    public AlbumVisibility() {
        this(DSL.name("album_visibility"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AlbumVisibilityRecord, Long> getIdentity() {
        return (Identity<AlbumVisibilityRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AlbumVisibilityRecord> getPrimaryKey() {
        return Internal.createUniqueKey(AlbumVisibility.ALBUM_VISIBILITY, DSL.name("pk_alvisibility"), new TableField[] { AlbumVisibility.ALBUM_VISIBILITY.ID }, true);
    }

    @Override
    public List<UniqueKey<AlbumVisibilityRecord>> getUniqueKeys() {
        return Arrays.asList(
            Internal.createUniqueKey(AlbumVisibility.ALBUM_VISIBILITY, DSL.name("uq_alvisibility_name"), new TableField[] { AlbumVisibility.ALBUM_VISIBILITY.NAME }, true)
        );
    }

    @Override
    public AlbumVisibility as(String alias) {
        return new AlbumVisibility(DSL.name(alias), this);
    }

    @Override
    public AlbumVisibility as(Name alias) {
        return new AlbumVisibility(alias, this);
    }

    @Override
    public AlbumVisibility as(Table<?> alias) {
        return new AlbumVisibility(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AlbumVisibility rename(String name) {
        return new AlbumVisibility(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AlbumVisibility rename(Name name) {
        return new AlbumVisibility(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AlbumVisibility rename(Table<?> name) {
        return new AlbumVisibility(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
