/*
 * This file is generated by jOOQ.
 */
package com.fenrir.core.database.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Albums implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String name;
    private final String description;
    private final LocalDateTime updatedAt;
    private final LocalDateTime createdAt;
    private final Long ownerId;
    private final Long visibilityId;

    public Albums(Albums value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.updatedAt = value.updatedAt;
        this.createdAt = value.createdAt;
        this.ownerId = value.ownerId;
        this.visibilityId = value.visibilityId;
    }

    public Albums(
        Long id,
        String name,
        String description,
        LocalDateTime updatedAt,
        LocalDateTime createdAt,
        Long ownerId,
        Long visibilityId
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.updatedAt = updatedAt;
        this.createdAt = createdAt;
        this.ownerId = ownerId;
        this.visibilityId = visibilityId;
    }

    /**
     * Getter for <code>public.albums.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.albums.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.albums.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>public.albums.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Getter for <code>public.albums.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>public.albums.owner_id</code>.
     */
    public Long getOwnerId() {
        return this.ownerId;
    }

    /**
     * Getter for <code>public.albums.visibility_id</code>.
     */
    public Long getVisibilityId() {
        return this.visibilityId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Albums other = (Albums) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.ownerId == null) {
            if (other.ownerId != null)
                return false;
        }
        else if (!this.ownerId.equals(other.ownerId))
            return false;
        if (this.visibilityId == null) {
            if (other.visibilityId != null)
                return false;
        }
        else if (!this.visibilityId.equals(other.visibilityId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.ownerId == null) ? 0 : this.ownerId.hashCode());
        result = prime * result + ((this.visibilityId == null) ? 0 : this.visibilityId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Albums (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(visibilityId);

        sb.append(")");
        return sb.toString();
    }
}
