/*
 * This file is generated by jOOQ.
 */
package com.fenrir.core.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Startup implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String name;
    private final String value;

    public Startup(Startup value) {
        this.name = value.name;
        this.value = value.value;
    }

    public Startup(
        String name,
        String value
    ) {
        this.name = name;
        this.value = value;
    }

    /**
     * Getter for <code>public.startup.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.startup.value</code>.
     */
    public String getValue() {
        return this.value;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Startup other = (Startup) obj;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.value == null) {
            if (other.value != null)
                return false;
        }
        else if (!this.value.equals(other.value))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Startup (");

        sb.append(name);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
