spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imagevault
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
          facebook:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/facebook
            authorization-grant-type: authorization_code
            scope: public_profile, email

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
    algorithm: PBEWITHHMACSHA512ANDAES_256

jwt:
  secret:
  expiration: 172800000